@baseUrl = https://dropsecure.onrender.com
@courier_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNjUwMWQ3Mi0wY2ZiLTQ0NDUtOTliNi0zYTNiZGY2NDBlMzMiLCJlbWFpbCI6Im1lbGlzc2Eud2FpdGl0dWhAc3RyYXRobW9yZS5lZHUiLCJyb2xlIjoiQ09VUklFUiIsImlhdCI6MTc1Mzc4MTc3MiwiZXhwIjoxNzUzODY4MTcyfQ.-SkXFXnwjyaE9JN-4h6x0VLo5wrG8FpIHAVl3P25MZE
@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5Njg5MzViMS01ZTliLTRkMGQtYTZiNS00MTY0Y2VjMWJlNTgiLCJlbWFpbCI6Im1lbGlzc2FtYWtlYmFAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzU0NDg4MDk2LCJleHAiOjE3NTQ1NzQ0OTZ9.vrvy5K8b925mPc4Dj2acye6-3ywewP2AegPZjlw2Kyo
@courierId = 607cbb4f-071e-40b5-af9a-acce739f0c5f
@packageId = 799a9df0-3478-4759-a4e2-120271ad376b


### Get Courier Profile (Courier)
GET {{baseUrl}}/courier/profile
Authorization: Bearer {{courier_token}}

### Get All Couriers (Admin)
GET {{baseUrl}}/courier/admin/couriers
Authorization: Bearer {{admin_token}}

### Get Available Couriers (Admin)
GET {{baseUrl}}/courier/admin/couriers/available
Authorization: Bearer {{admin_token}}

### Verify Courier (Admin)
PUT {{baseUrl}}/courier/admin/courier/{{courierId}}/verify
Authorization: Bearer {{admin_token}}

### Update Courier Status (Admin)
PUT {{baseUrl}}/courier/admin/courier/{{courierId}}/status
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "status": "AVAILABLE",
  "currentLat": 6.5244,
  "currentLng": 3.3792
}

### Update Courier Status (Admin) with packageId
PUT {{baseUrl}}/courier/admin/courier/{{courierId}}/status
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "status": "AVAILABLE",
  "currentLat": 6.5244,
  "currentLng": 3.3792,
  "packageId": "{{packageId}}"
}

### Update Courier Location (Courier)
PUT {{baseUrl}}/courier/location
Authorization: Bearer {{courier_token}}
Content-Type: application/json

{
  "currentLat": 6.5244,
  "currentLng": 3.3792
}